name: 02 CI Workflow

on:
  push:
    paths:
      - "app/**"
      - "tests/**"
      - ".github/workflows/02-ci.yml"
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v6

      - name: Read Python versions from secret
        run: |
          echo "VERSIONS=${{ secrets.PYTHON_VERSIONS }}" >> $GITHUB_ENV

      - name: Run tests for each version
        run: |
          for version in $(echo $VERSIONS | tr ',' ' '); do
            echo "Running tests on Python $version"
            
            # تثبيت بايثون
            pyenv install -s $version
            pyenv global $version
            
            python --version
            
            # تشغيل التست
            python -m unittest discover -s tests -v
          done
